languageCode = "vi"
languageName = "Vietnamese"
weight = 1
title = "hpnguyendendogram"

[params]
  displayName = "VI"
  isoCode = "vi"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/circledendogram.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "Xin chào mọi người, mình là Hoàng Phước Nguyên, mọi người cũng có gọi mình là Alex (tên nghe tây tây chút để mai mốt có gì vươn ra biển lớn thôi) hoặc là Nguyên (cái tên mình, cũng là cái tên mình yêu nhất) đều được. Mình thích viết, viết về mọi thứ, viết về mọi chủ đề nên đảm bảo không làm các bạn chán nếu tham quan blog nhỏ này của mình đâu."
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Hoàng Phước Nguyên"
  image = "img/hpnguyendendogram.png"
  headline = "Mọi việc khó, không có Nguyên lo!!!"
  #bio = "A little bit about you"
  links = [
    { email = "nguyenhoang0106hpn@gmail.com" },
    { link = "https://hpnguyendendogram.github.io/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
    { facebook = "https://www.facebook.com/AlexKhia.Nguyen0106/" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/hpnguyendendogram" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
  ]
